pipeline:
  name: Build go-pipeline-sample
  identifier: Build_go_pipeline_sample_1689234136805
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1689233993319
        repoName: parvathijoshi/go-pipeline-sample
        build: <+input>
